spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/planet_web_registration?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtps.aruba.it
    username: planets@planets.community
    password: GoodPlanet2023!!
    port: 465
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
          timeout: 5000
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
server:
  port: 9000
planet:
  mail:
    sender: ddstechnologyzone@gmail.com
    senderName: PLANET WEB
    subject: Registration Verification Code
  context: /api/v1/users/hashCodeVerify/
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
info:
  app:
    name: Registration Service
    description: planet web registration service
    version: 1.0.0
    
keycloak:
  cors: true
  auth-server-url: http://80.211.143.200:8080
  realm: master
  resource: edcs-user-auth
  ssl-required: none
  public-client: true
  credentials.secret: 348c0f3f-49cb-4cd4-8d3a-978ef43b437e
  client_id: planet-client
  adminuser: user
  adminpassword: 123456
  grant_type: password
