spring:
  config:
    enabled: true
    import: optional:configserver:http://localhost:8091
  application:
    name: discovery
  profiles:
    active: local
server:
  port: 8072      
info:
  app:
    name: Service Discovery
    description: Planet Web Service Discovery
    version: 1.0.0


