server:
  port: 8090

spring:
  application:
      name: statistics-service
  datasource:
    url: jdbc:mysql://localhost:3306/statistics_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka