spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://80.211.143.200:3307/planet_web_registration?createDatabaseIfNotExist=true
    username: planet
    password: planet
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
keycloak:
  cors: true
  auth-server-url: http://80.211.143.200:8080
  realm: master
  resource: edcs-user-auth
  ssl-required: none
  public-client: true
  credentials.secret: 348c0f3f-49cb-4cd4-8d3a-978ef43b437e
  security-constraints[0]:
    authRoles[0]: default-roles-edcs
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  client_id: planet-client
  adminuser: user
  adminpassword: 123456
  grant_type: password
